Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vbguest.installer_options = { allow_kernel_upgrade: true }

  config.vm.define "mgmt" do |mgmt|
      mgmt.vm.network "private_network", ip:"10.0.26.200"
      mgmt.vm.hostname = "mgmt"
      mgmt.vm.box = "centos/7"
      mgmt.vm.synced_folder ".", "/vagrant", disabled: true
      mgmt.vm.box_check_update = false
      mgmt.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
        vb.name = "mgmt"
      end
      mgmt.vm.provision "shell", inline: "service network restart"
      mgmt.vm.provision "shell", inline: "sed -i '/PasswordAuthentication/s/no/yes/' /etc/ssh/sshd_config"
      mgmt.vm.provision "shell", inline: "service sshd restart"
      mgmt.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
      mgmt.vm.provision "file", source: "provision", destination: "/home/vagrant/"
      mgmt.vm.provision "shell", inline: "yum -y install dos2unix"
      mgmt.vm.provision "shell", inline: "find /home/vagrant/ -type f -print0 | xargs -0 dos2unix"
      mgmt.vm.provision "shell", inline: "chmod +x /home/vagrant/provision/aws/inventory/ec2*.*"
      mgmt.vm.provision "shell", path: "shell/ansible-setup.sh"
  end
end