---
- hosts: localhost
  vars_files:
      - secret/aws_credentials.yml
  tasks:
     - name: "refresh invntory"
       meta: refresh_inventory

- hosts: tag_name_webserver
  tasks:
     - name: "Installing Apache Webserver"    
       package:
           name: "httpd"
           state: present


     - name: "Installing php software"        
       package:
           name: "php"
           state: present

     - name: "Copy webpage"
       copy:
           dest: "/var/www/html/index.php"
           content: |
                   <pre>
                   <?php

                   print `/usr/sbin/ifconfig`;

                   ?>
                   </pre>

     - name: "start http server"
       service:
             name: "httpd"
             state: started

- hosts: tag_name_loadbalancer
  vars:
      - service_port: 8080
  tasks:
      - name: Installing Reverse proxy software""
        package:
            name: "haproxy"
            state: present

      - name: "Copying configuration file"
        template:
            src: "haproxy.cfg.j2"
            dest: "/etc/haproxy/haproxy.cfg"
        notify: "restart LB"


  handlers:
      - name: "restart LB"
        service:
            name: "haproxy"
            state: restarted
            enabled: yes
